# Generated by Django 5.2.7 on 2025-10-14 02:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id_categoria', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'categoria',
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id_ubicacion', models.AutoField(primary_key=True, serialize=False)),
                ('sector', models.CharField(max_length=128)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'ubicacion',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=14)),
            ],
            options={
                'db_table': 'usuario',
            },
        ),
        migrations.CreateModel(
            name='Incidencia',
            fields=[
                ('id_incidencia', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=400)),
                ('fecha_reporte', models.DateTimeField()),
                ('imagen', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(max_length=10)),
                ('id_categoria', models.ForeignKey(db_column='id_categoria', on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.categoria')),
                ('id_ubicacion', models.ForeignKey(db_column='id_ubicacion', on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.ubicacion')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.usuario')),
            ],
            options={
                'db_table': 'incidencia',
            },
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id_respuesta', models.AutoField(primary_key=True, serialize=False)),
                ('comentario', models.CharField(max_length=350)),
                ('fecha', models.DateTimeField()),
                ('id_incidencia', models.ForeignKey(db_column='id_incidencia', on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.incidencia')),
                ('id_usuario', models.ForeignKey(db_column='id_usuario', on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.usuario')),
            ],
            options={
                'db_table': 'respuesta',
            },
        ),
    ]
