# Generated by Django 5.1.5 on 2025-10-14 14:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='incidencia',
            options={'ordering': ['-fecha_reporte']},
        ),
        migrations.AddField(
            model_name='incidencia',
            name='categoria_texto',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='django_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='titulo',
            field=models.CharField(default='Sin título', max_length=200),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='ubicacion_texto',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='incidencia',
            name='urgencia',
            field=models.CharField(default='media', max_length=10),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('progreso', 'En Progreso'), ('resuelto', 'Resuelto'), ('cerrado', 'Cerrado')], default='pendiente', max_length=10),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='fecha_reporte',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='incidencia',
            name='id_usuario',
            field=models.ForeignKey(blank=True, db_column='id_usuario', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='reportes.usuario'),
        ),
    ]
