# Generated by Django 5.2.6 on 2025-10-14 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reportes', '0002_alter_incidencia_options_incidencia_categoria_texto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='incidencias/'),
        ),
    ]
