# Generated by Django 4.1.7 on 2025-12-02 17:19

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('reportes', '0003_incidencia_foto'),
    ]

    operations = [
        migrations.CreateModel(
            name='UsuarioReportador',
            fields=[
            ],
            options={
                'verbose_name': 'UsuariosR',
                'verbose_name_plural': 'UsuariosR',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('estudiante', 'Estudiante'), ('encargado', 'Encargado')], help_text='Categoría del rol', max_length=50, unique=True)),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del rol')),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('actualizado', models.DateTimeField(auto_now=True)),
                ('usuarios', models.ManyToManyField(blank=True, help_text='Usuarios asignados a este rol', related_name='roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'ordering': ['nombre'],
            },
        ),
    ]
